### ISSUE TITLE
Issue of training on multi-GPUs 

### ISSUE THREAD

**Issue by CloudHerods** [Zx55/dmcp#8]
When i set distributed_enable=False and  train on multi-GPUs, error happend. But single GPU work.
======================================
Traceback (most recent call last):
  File "main.py", line 71, in <module>
    main()
  File "main.py", line 54, in main
    train(config, runner, loaders, checkpoint, tb_logger)
  File "main.py", line 30, in train
    runner.train(train_loader, val_loader, optimizer, lr_scheduler, tb_logger)
  File "/home/Brin1/dmcp-master/runner/dmcp_runner.py", line 46, in train
    self._train_one_batch(x, y, optimizer, lr_scheduler, meters, criterions, end)
  File "/home/Brin1/dmcp-master/runner/dmcp_runner.py", line 145, in _train_one_batch
    criterions, end)
  File "/home/Brin1/dmcp-master/runner/us_runner.py", line 201, in _train_one_batch
    out = self.model(x)
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 142, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 147, in replicate
    return replicate(module, device_ids)
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/replicate.py", line 53, in replicate
    param_idx = param_indices[param]
KeyError: Parameter containing:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       device='cuda:0', requires_grad=True)

thanks!

**Comment by Zx55** [comment]
you may set

```yaml
distributed:
    enable:
        True
```

if you want to train on multi gpus.

**Comment by CloudHerods** [comment]
thank you very much! 
but i it only just run on  one gpu. I don't know how pytorch distribution work. 
i modified distribution code like below:
=========================================
        # for environment variable
        else:
            rank = int(os.environ['RANK']) if 'RANK' in os.environ else 0
            world_size = int(os.environ['WORLD_SIZE']) if 'WORLD_SIZE' in os.environ else 1
            url = 'tcp://localhost:23456'
            #url = None
===================
thanks!

**Comment by Zx55** [comment]
if you run code on multi nodes, maybe you can pass ip and port of master node (e.g: "tcp://10.10.10.1:8000") through command line args 

```bash
# on master  
CUDA_VISIBLE_DEVICES=0 RANK=0 WORLD_SIZE=2 python main.py --url tcp://10.10.10.1:8000 ...

# on slave
CUDA_VISIBLE_DEVICES=0 RANK=1 WORLD_SIZE=2 python main.py --url tcp://10.10.10.1:8000 ...
```

don't forget to add argments to parser in `main.py` and set it [here](https://github.com/Zx55/dmcp/blob/master/utils/distributed.py#L31)

or just use slurm 
    
```bash
srun --partition=YOUR_PARTITION --mpi=pmi2 --gres=gpu:4 -n12 --ntasks-per-node=4 --job-name=dmcp --kill-on-bad-exit=1 python main.py ...
```

**Comment by CloudHerods** [comment]
thank you very much and i will have a try.
